project:
  type: website
  resources:
  - "images/*"
  output-dir: docs

website:
  title: "alexclaydon.dev"
  site-url: https://alexclaydon.dev
  description: "Technical blog of Alex Claydon, Head of Data and AI Strategy at Lexical Labs"
  back-to-top-navigation: true
  page-footer: "Copyright 2025, Alex Claydon"
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/alex-claydon-9369723/
      - icon: twitter
        href: https://x.com/aclaydon_dev
      - icon: github
        href: https://github.com/alexclaydon
      - icon: rss
        href: index.xml
      - about.qmd
format:
  html:
    theme:
      - minty
